added content to README.md file, added jpeg of logo to the repository
redhat-beyond/HighTeach pull request #1
Opened 2023-03-15 11:17 UTC by idan1356

README file consists of:
- project description section
- dependencies and how to run project
- contribution and license
- team members

2023-03-16 11:14 UTC, Omeramsc requested changes
I like the work with issues, keep it up! 
The title of the PR should not be that complicated, I think adding the logo can be considered as part of what been added to the README. "Useful information in README" (or something along those lines) is a fine name

2023-03-16 11:25 UTC, natifridman commented on README.md
> +Please see our CONTRIBUTING.md file for details on how to contribute.
You can always create another PR to add it to the README

2023-03-20 08:31 UTC, Omeramsc approved these changes
LGTM :)

2023-03-20 08:40 UTC, natifridman commented
Waiting for 2 students' reviews

2023-03-20 13:28 UTC, shirazyomtov approved these changes
LGTM

2023-03-20 16:49 UTC, natifridman approved these changes
LGTM

2023-03-20 17:14 UTC, merged