Improve UI in course pages
redhat-beyond/HighTeach pull request #114
Opened 2023-06-01 17:37 UTC by RanyWh

**Imporving the UI in the course related pages.**

**Changes made :**

- Add photo to the add course page
- Add style to add course page
- Add style to course table page
- Connect teacher photo in the course page
- Fix bug where the course icon wasn't working in course page
- Show course table according to user (teacher/student/both)
- Add request to join course tab in course page
- Add column to show how many request to join there is in a course 
- Adjust tests to changes

Course table page :

![image](https://github.com/redhat-beyond/HighTeach/assets/115880394/7374f628-ca19-48dc-b3ef-19bd3b7814d7)

Add course page :

![צילום מסך 2023-06-01 204036](https://github.com/redhat-beyond/HighTeach/assets/115880394/271bbf3e-0bb2-4a9a-bb75-2d3a250db577)

Course page:
![image](https://github.com/redhat-beyond/HighTeach/assets/115880394/e57bd886-8079-4332-94cd-ba259db2157c)

fixes #117

2023-06-04 05:34 UTC, shirazyomtov requested changes
Great work, left a few comments.

2023-06-04 05:34 UTC, shirazyomtov commented on course/templates/course/courses_two_tables.html
> +            <!-- <button type="button" class="btn btn-success" style="float: right;">Add Course</button></a> -->
Please remove this comment

2023-06-04 05:34 UTC, shirazyomtov commented on static/styles/courses.table.css
> +}
Missing a new line at the end of the file

2023-06-04 05:34 UTC, shirazyomtov commented on static/styles/student_course.css
> +} */
Please remove this comment

2023-06-04 05:34 UTC, shirazyomtov commented on tests/course/test_course_pages.py
>      return client
Maybe we could move the fixtures to the conftest.py

2023-06-04 05:34 UTC, shirazyomtov commented on course/templates/course/courses_table.html
> +            <!-- <button type="button" class="btn btn-success" style="float: right;">Add Course</button></a> -->
Please remove this comment

2023-06-05 19:08 UTC, Davidco94 approved these changes
LGTM

2023-06-05 19:20 UTC, shirazyomtov approved these changes
LGTM

2023-06-06 05:59 UTC, galitf commented
I would split this MR according to the UI pages you are  improving: Add course page, course table page and course page.  Usually fixing a bug should be in a separate MR.

2023-06-06 09:04 UTC, Omeramsc approved these changes
This patch includes way too many changes and additions and can probably split to multiple PRs, as Galit suggested. But... as we are in the final week of the project, we better let it slide; do note that on your future works.

2023-06-06 12:14 UTC, natifridman approved these changes
LGTM

2023-06-06 12:20 UTC, merged