Add requests to course page
redhat-beyond/HighTeach pull request #115
Opened 2023-06-03 22:44 UTC by RanyWh

**This PR's goal is to give the course owner the ability to accept or decline requests from students to join the course.
The requests are shown inside the course page in the join course tab that's only visible for the teacher.**

Steps:

- Add student_course.html
- Add student_course.css
- Include student_course.html in course page
- Add in views and urls AcceptOrDeclineStudentCourse class
- Added tests for the accept and decline options

Course Page join course tab :
![צילום מסך 2023-06-04 011651](https://github.com/redhat-beyond/HighTeach/assets/115880394/1abbc23a-08b5-4ea5-b88c-21ae8839011b)

dependencies  #114 
fixes #116

2023-06-04 05:43 UTC, shirazyomtov requested changes
Great work, left a few comments

2023-06-04 05:43 UTC, shirazyomtov commented on course/templates/course/course_page.html
There are leftover from the confict in git, Please remove this

2023-06-04 05:43 UTC, shirazyomtov commented on course/templates/course/course_page.html
>              </div>
same as above

2023-06-04 05:43 UTC, shirazyomtov commented on course/templates/course/courses_table.html
> +            <!-- <button type="button" class="btn btn-success" style="float: right;">Add Course</button></a> -->
Please remove this comment

2023-06-04 05:43 UTC, shirazyomtov commented on course/templates/course/courses_two_tables.html
> +            <button class="icon-btn add-btn">
Please remove this comment

2023-06-04 05:43 UTC, shirazyomtov commented on static/styles/courses.table.css
> +}
Missing a new line at the end of the file

2023-06-04 05:43 UTC, shirazyomtov commented on static/styles/student_course.css
> +>>>>>>> ead046d (Ui improvment)
There are leftover from the confict in git, Please remove this

2023-06-04 05:43 UTC, shirazyomtov commented on static/styles/student_course.css
> +>>>>>>> ead046d (Ui improvment)
There are leftover from the confict in git, Please remove this

2023-06-04 05:43 UTC, shirazyomtov commented on tests/course/test_course_pages.py
> +    client.force_login(persist_profile_teacher_and_student.user)
Same comment as in this [PR](https://github.com/redhat-beyond/HighTeach/pull/114#discussion_r1216229754)

2023-06-05 19:09 UTC, Davidco94 submitted a review, later dismissed
LGTM

2023-06-05 19:19 UTC, shirazyomtov submitted a review, later dismissed
LGTM

2023-06-06 09:16 UTC, Omeramsc requested changes

2023-06-06 09:16 UTC, Omeramsc commented on course/views.py
> +        if request.user.profile.account_type == 'B':
A lot of conditional... where is the test that verify it works as expected?

2023-06-06 09:16 UTC, Omeramsc commented on tests/course/test_course_pages.py
> +        assert not StudentCourse.objects.filter(student_course_id=student_course_id).exists()
what about the student_course0.statue.value? does the request itself exists? is it "Rejected"?

2023-06-06 11:52 UTC, Omeramsc commented on tests/course/test_course_pages.py
> +        assert not StudentCourse.objects.filter(student_course_id=student_course_id).exists()
Sounds like a bug. how the student can know about his request status? I'd argue it should be changed to "Rejected"...

2023-06-07 08:17 UTC, Omeramsc commented on tests/course/test_course_pages.py
> +        assert not StudentCourse.objects.filter(student_course_id=student_course_id).exists()
Very good! I left one comment regarding the test, fix that and it is ready IMO

2023-06-07 09:24 UTC, Omeramsc submitted a review, later dismissed
LGTM, Good job

2023-06-07 10:18 UTC, shirazyomtov approved these changes, later dismissed
LGTM

2023-06-07 11:41 UTC, natifridman reviewed
Looks good, please resolve conflicts

2023-06-07 13:04 UTC, shirazyomtov approved these changes
LGTM

2023-06-07 13:22 UTC, Omeramsc approved these changes

2023-06-07 13:22 UTC, merged