Adding CI - Flake8
redhat-beyond/HighTeach pull request #13
Opened 2023-03-21 21:03 UTC by Yardengz

Add GitHub actions configuration
set GitHub to run Flake8 on the code as we submit new PRs

2023-03-21 21:25 UTC, Davidco94 approved these changes
LGTM

2023-03-22 09:01 UTC, idan1356 approved these changes
LGTM

2023-03-22 09:05 UTC, shirazyomtov approved these changes
LGTM

2023-03-22 09:49 UTC, natifridman requested changes
Overall looks good. Added one comment

2023-03-22 09:49 UTC, natifridman commented on .github/workflows/flake8.yml
> +        run: pipenv run flake8 --max-line-length 120
Missing newline at end of file

2023-03-22 14:06 UTC, Yardengz commented on .github/workflows/flake8.yml
> +        run: pipenv run flake8 --max-line-length 120
fixed, please confirm.

2023-03-22 14:07 UTC, Yardengz commented on .github/workflows/flake8.yml
> +        run: pipenv run flake8 --max-line-length 120
fixed, please confirm.

2023-03-22 14:29 UTC, natifridman requested changes

2023-03-22 22:22 UTC, Yardengz commented on .github/workflows/flake8.yml
> +
i fixed this.

2023-03-23 09:23 UTC, natifridman approved these changes
LGTM. Please squash the commits so we can merge it

2023-03-23 13:11 UTC, natifridman requested changes
Looks like the flake8 installation was removed from this PR

2023-03-23 19:49 UTC, Yardengz commented on .github/workflows/flake8.yml
> +
Fixed, please approve

2023-03-26 14:20 UTC, natifridman approved these changes
LGTM

2023-03-26 14:21 UTC, merged