Add chat tests and update validation of message creation.
redhat-beyond/HighTeach pull request #60
Opened 2023-04-19 20:30 UTC by shacharlevy

This includes:
- Validating that a chat message was sent by a valid user before saving it (i.e. by a member of a study group and not by someone outside the group, or by the teacher or student of a private lesson).
- Tests for the ChatManager.
- Tests for the chat's Message model.

The chat app is dependant on the StudyGroup and Course apps, which are not merged as of now. For this reason, the tests and Model fields related to those apps are commented out.
The tests have been ran locally and passed with the changes in the other apps PRs (which are not added as part of this PR). After the merging of the other apps and conflicts resolution the commented out fields and tests will be restored.

2023-04-20 06:03 UTC, shirazyomtov approved these changes
LGTM

2023-04-20 13:47 UTC, natifridman commented
Please resolve conflicts

2023-04-20 14:40 UTC, shacharlevy commented
> Please resolve conflicts

Done

2023-04-20 14:53 UTC, shirazyomtov approved these changes
LGTM

2023-04-20 15:24 UTC, idan1356 submitted a review, later dismissed
LGTM

2023-04-20 17:31 UTC, natifridman requested changes
I think you can uncomment the code now that #47 is merged

2023-04-20 18:09 UTC, shacharlevy commented on chat/migrations/0001_initial.py
Done :)

2023-04-20 18:25 UTC, shacharlevy commented on chat/migrations/0001_initial.py
Done :)

2023-04-20 18:34 UTC, idan1356 approved these changes
LGTM

2023-04-23 15:57 UTC, natifridman commented on chat/migrations/0001_initial.py
Looks like there are still changes in this file

2023-04-23 20:14 UTC, shacharlevy commented on chat/migrations/0001_initial.py
Done again :)

2023-04-24 10:12 UTC, natifridman reviewed
Looks good, I added some comments

2023-04-24 10:12 UTC, natifridman commented on chat/models.py
> +    group = models.ForeignKey(StudyGroup, on_delete=models.CASCADE, blank=True, null=True)
Why do you need `blank=True` and `null=True`? I think that's the default...

2023-04-24 10:12 UTC, natifridman commented on chat/models.py
> +            raise ValidationError({'sender': "The message sender is not the teacher or the student of the course."})
Maybe you can use [constraints](https://stackoverflow.com/questions/46286089/specific-way-of-requiring-one-of-two-fields-in-django-model-definition) instead?

2023-04-24 10:12 UTC, natifridman commented on tests/conftest.py
Maybe you can use the fixtures that are already in this file?

2023-04-25 11:54 UTC, shirazyomtov submitted a review, later dismissed
LGTM

2023-04-27 07:08 UTC, natifridman commented on tests/conftest.py
I think you can do it in this PR if there are already fixtures doing the same thing and it's just changing the names in your tests

2023-04-28 20:10 UTC, shacharlevy commented on tests/conftest.py
Ok :) I used the two users fixtures that were already in the conftest file. I kept the study_group0 although there is a study_group fixture in this file because this time the owner is part of the group.

2023-04-29 08:27 UTC, idan1356 submitted a review, later dismissed
LGTM

2023-04-29 08:59 UTC, shirazyomtov approved these changes
LGTM

2023-04-30 08:55 UTC, natifridman approved these changes
LGTM, please squash the commits

2023-04-30 09:21 UTC, shacharlevy commented
> LGTM, please squash the commits

Done

2023-04-30 09:37 UTC, shirazyomtov approved these changes
LGTM

2023-05-01 07:26 UTC, natifridman approved these changes

2023-05-01 07:27 UTC, merged