Create Add Course page
redhat-beyond/HighTeach pull request #84
Opened 2023-05-14 03:38 UTC by RanyWh

**Added a Add Course page to the website that presents the form of the Course**

**Changes :** 
- Add to course/urls a path for the /course/add
- Add a AddCourse class to the views.py with a get and post to handle requests
- Add a form.py to connect between the display and the module
- Add the add_course.html file in templates
- Add the course.add.css to style the add_course.html
- Add the path to the Add Course button in courses.html to send to /course/add

dependencies #83 
fixes #92 

The website :

![image](https://github.com/redhat-beyond/HighTeach/assets/115880394/4c8f6356-aab0-4327-960b-ba0beb8a51a1)

2023-05-16 16:12 UTC, shirazyomtov reviewed
Great work, I made some comments

2023-05-16 16:12 UTC, shirazyomtov commented on course/templates/course/add_course.html
> +
Could you delete these empty lines

2023-05-16 16:12 UTC, shirazyomtov commented on course/templates/course/courses.html
> +
Same as above

2023-05-16 16:12 UTC, shirazyomtov commented on main/templates/base_home.html
>      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet"
Please change the name of the folder of CSS files to match what appears in the static folder or we can decide on one name for the css folders(There are several PRs with different names for the css folder)

2023-05-16 22:05 UTC, shirazyomtov approved these changes
LGTM

2023-05-16 22:18 UTC, Davidco94 submitted a review, later dismissed
LGTM

2023-05-17 07:43 UTC, natifridman commented on course/urls.py
> +    path('add', AddCourse.as_view(), name="addCourse"),
Can we try to be consistent in the name convention?

2023-05-17 07:45 UTC, natifridman commented on tests/course/test_course_pages.py
> +        assert course_response.status_code == 200
Maybe we can also check the template in the response?

2023-05-17 07:45 UTC, natifridman commented on tests/course/test_course_pages.py
> +        assert course_response.status_code == 302
Maybe we can also check the template in the response or the response URL?

2023-05-17 07:46 UTC, natifridman commented on tests/course/test_course_pages.py
> +        assert course_creation_response.status_code == 302
Maybe we can also check the template in the response or the response URL?

2023-05-17 09:12 UTC, Omeramsc requested changes
left some comments, overall great work. I liked the use of the |= operator.

2023-05-17 09:12 UTC, Omeramsc commented on tests/course/test_course_pages.py
> +        assert any(persist_first_student_course.pk == course.pk for course in response.context['courses'])
for the sake of readability, assign the comprehensions to a variable with a clear name

2023-05-17 09:12 UTC, Omeramsc commented on tests/course/test_course_pages.py
> +        assert any(teacher_course_zero.pk == course.pk for course in response.context['courses'])
for the sake of readability, assign the comprehensions to a variable with a clear name

2023-05-17 09:12 UTC, Omeramsc commented on tests/course/test_course_pages.py
> +        assert course_response.status_code == 302
Maybe we can also check the template in the response or the response URL?

2023-05-17 09:12 UTC, Omeramsc commented on tests/course/test_course_pages.py
> +        assert course_response.status_code == 200
Maybe we can also check the template in the response or the response URL?

2023-05-17 13:15 UTC, shirazyomtov commented
Please resolve conflicts

2023-05-18 06:38 UTC, galitf commented
please fix the conflicts

2023-05-18 09:22 UTC, natifridman approved these changes
LGTM

2023-05-18 09:25 UTC, shirazyomtov approved these changes
LGTM

2023-05-18 09:25 UTC, idan1356 approved these changes
LGTM

2023-05-18 11:26 UTC, merged